# Versioned
deps.java=25
deps.cloth=126.1.154
deps.owo=0.13.0+26.1
deps.fapi=0.151.0+26.1.2
deps.modmenu=18.0.0-beta.1
deps.cicada=0.15.1+26.1

# Mod
mod.mc_dep=26.1
mod.mc_title=26.1
mod.mc_targets=26.1
mod.target_min=26.1
mod.target_max=26.1
minecraft_version=26.1

deps.fabric_loader=0.15.11
mod.version=1.4.4
mod.group=dev.enjarai
mod.id=moderate-loading-screen
mod.name=Mod-erate Loading Screen
mod.modrinth=RCjGlCDj
mod.curseforge=557180
mod.github=enjarai/moderate-loading-screen
